import type { L10n } from "./site";

export type ServiceNarrative = {
  fitFor: L10n[];
  problems: L10n[];
  method: { title: L10n; description: L10n }[];
  promise: L10n;
};

const l = (vi: string, en: string): L10n => ({ vi, en });

export const serviceNarrativeBySlug: Record<string, ServiceNarrative> = {
  "esports-gaming-marketing-sea": {
    fitFor: [l("Studio quốc tế chuẩn bị vào Việt Nam hoặc Đông Nam Á", "International studios entering Vietnam or Southeast Asia"), l("Game cần creator và cộng đồng phù hợp theo từng thị trường", "Games needing market-specific creators and communities"), l("Đội ngũ muốn một đối tác kết nối influencer, PR và UA", "Teams needing one partner across influencer, PR and UA")],
    problems: [l("Một thông điệp quốc tế không tạo được sự liên quan ở từng nước", "One international message lacks relevance in each market"), l("Danh sách influencer lớn nhưng không đúng thể loại hoặc tệp người chơi", "Large influencer lists without genre or audience fit"), l("Launch tạo lượt xem nhưng thiếu activation và retention", "Launches generate views but not activation or retention")],
    method: [{ title: l("Đọc bản đồ cộng đồng", "Read the community map"), description: l("Phân tích thể loại, nền tảng, ngôn ngữ và vai trò của creator tại từng thị trường SEA.", "Analyze genre, platform, language and creator roles in each SEA market.") }, { title: l("Thiết kế chiến dịch bản địa", "Design the local campaign"), description: l("Xây message, format, creator brief và nhịp PR phù hợp với văn hóa và hành vi từng quốc gia.", "Build messages, formats, briefs and PR cadence around each country's culture and behavior.") }, { title: l("Đo và tối ưu theo cohort", "Measure by cohort"), description: l("Theo dõi từ reach đến install, activation, retention và chất lượng thảo luận để phân bổ lại ngân sách.", "Track reach through installs, activation, retention and conversation quality to reallocate budget.") }],
    promise: l("ANBU giúp game bước vào Đông Nam Á như một phần của cộng đồng địa phương, không phải một quảng cáo được dịch sang nhiều ngôn ngữ.", "ANBU helps games enter Southeast Asia as part of local communities, not as one advertisement translated into many languages."),
  },
  "influencer-marketing": {
    fitFor: [
      l("Thương hiệu chuẩn bị ra mắt sản phẩm hoặc bước vào Việt Nam", "Brands launching a product or entering Vietnam"),
      l("Chiến dịch cần nhiều lớp creator: celebrity, KOL, KOC và community", "Campaigns requiring a mix of celebrities, KOLs, KOCs and communities"),
      l("Đội ngũ cần một đầu mối quản lý booking, nội dung và báo cáo", "Teams needing one owner for booking, content and reporting"),
    ],
    problems: [
      l("Nhiều lượt xem nhưng thông điệp thương hiệu không được nhớ", "High views but weak brand recall"),
      l("Creator phù hợp hình ảnh nhưng không phù hợp tệp người xem", "Creators fit the image but not the audience"),
      l("Nội dung bị rời rạc, khó kiểm soát lịch đăng và chất lượng", "Fragmented content, timelines and quality control"),
    ],
    method: [
      { title: l("Lập bản đồ ảnh hưởng", "Map influence"), description: l("Phân nhóm creator theo vai trò: tạo nhận biết, giải thích sản phẩm, kích hoạt thảo luận hay thúc đẩy hành động.", "Assign creators a clear role: awareness, education, conversation or action.") },
      { title: l("Thiết kế câu chuyện", "Design the story"), description: l("Xây content territory, key message và briefing đủ chặt để nhất quán nhưng vẫn giữ tiếng nói tự nhiên của creator.", "Build content territories, messages and briefs that stay consistent without losing each creator's voice.") },
      { title: l("Vận hành & tối ưu", "Operate and optimize"), description: l("Quản lý booking, duyệt nội dung, lịch đăng, social listening và tổng hợp bài học cho đợt tiếp theo.", "Manage booking, approvals, publishing, social listening and learnings for the next wave.") },
    ],
    promise: l("Không chỉ booking người nổi tiếng. ANBU thiết kế một hệ thống ảnh hưởng trong đó mỗi creator đều có lý do để xuất hiện và một nhiệm vụ rõ ràng trong hành trình ra mắt.", "More than talent booking. ANBU builds an influence system where every creator has a reason to appear and a clear job in the launch journey."),
  },
  "game-app-marketing": {
    fitFor: [l("Game hoặc ứng dụng chuẩn bị mở đăng ký, CBT/OBT hay ra mắt chính thức", "Games or apps approaching pre-registration, beta or official launch"), l("Sản phẩm quốc tế cần bản địa hóa để vào thị trường Việt Nam", "International products localizing for Vietnam"), l("Live product cần tái kích hoạt người chơi và cộng đồng", "Live products needing player and community reactivation")],
    problems: [l("Có media plan nhưng thiếu một câu chuyện ra mắt thống nhất", "A media plan without one coherent launch story"), l("Nhiều kênh chạy đồng thời nhưng creator, social, PR và UA không hỗ trợ nhau", "Creator, social, PR and UA channels working in silos"), l("Tải về ban đầu tốt nhưng thảo luận cộng đồng giảm nhanh", "Strong initial installs followed by fading community conversation")],
    method: [
      { title: l("Giải mã động lực người chơi", "Decode player motivation"), description: l("Xác định fantasy, tính năng và khoảnh khắc khiến từng nhóm người chơi muốn thử, quay lại hoặc rủ bạn bè.", "Identify the fantasy, features and moments that make each player segment try, return or invite friends.") },
      { title: l("Thiết kế nhịp ra mắt", "Engineer the launch rhythm"), description: l("Kết nối teaser, pre-registration, reveal, launch day và sustain thành một đường dây nội dung liên tục.", "Connect teaser, pre-registration, reveal, launch day and sustain into one continuous narrative.") },
      { title: l("Kích hoạt hệ sinh thái", "Activate the ecosystem"), description: l("Phối hợp KOL/KOC, gaming community, social, báo chí và paid media theo đúng vai trò từng kênh.", "Coordinate creators, gaming communities, social, press and paid media by channel role.") },
    ],
    promise: l("ANBU xem ra mắt game là một chuỗi khoảnh khắc cần được dàn dựng, không phải một ngày chạy quảng cáo. Mục tiêu là tạo lý do để cộng đồng chú ý, tham gia và tiếp tục ở lại.", "ANBU treats a game launch as a sequence of designed moments, not a single advertising day, giving the community reasons to notice, join and stay."),
  },
  "brand-strategy": {
    fitFor: [l("Thương hiệu mới cần định vị trước khi đầu tư truyền thông", "New brands defining their position before media investment"), l("Thương hiệu đang mở rộng nhưng thông điệp thiếu nhất quán", "Growing brands with inconsistent messaging"), l("Sản phẩm quốc tế cần tìm cách nói phù hợp với người Việt", "International products finding a locally relevant voice")],
    problems: [l("Khách hàng biết sản phẩm nhưng không hiểu vì sao nên chọn", "People know the product but not why they should choose it"), l("Mỗi kênh đang kể một phiên bản khác nhau về thương hiệu", "Every channel tells a different brand story"), l("Định vị nghe hay nhưng khó chuyển thành nội dung và hành động", "A positioning that sounds good but cannot guide execution")],
    method: [{ title: l("Tìm sự thật thị trường", "Find the market truth"), description: l("Đọc bối cảnh cạnh tranh, hành vi và khoảng trống nhận thức có thể sở hữu.", "Read competition, behavior and the perceptual space the brand can own.") }, { title: l("Chốt lựa chọn chiến lược", "Make the strategic choice"), description: l("Xác định đối tượng ưu tiên, giá trị khác biệt, lý do tin và tính cách thương hiệu.", "Define the priority audience, difference, reasons to believe and personality.") }, { title: l("Biến chiến lược thành công cụ", "Turn strategy into tools"), description: l("Chuyển định vị thành message house, content pillars và nguyên tắc để đội ngũ có thể dùng hằng ngày.", "Translate positioning into a message house, content pillars and everyday decision rules.") }],
    promise: l("Một chiến lược tốt phải giúp đội ngũ đưa ra quyết định nhanh hơn: nói gì, không nói gì, dành ngân sách ở đâu và nhất quán như thế nào.", "A good strategy helps teams decide faster: what to say, what not to say, where to invest and how to stay consistent."),
  },
  "creative-design": {
    fitFor: [l("Chiến dịch cần big idea và hệ thống key visual đa kênh", "Campaigns needing a big idea and cross-channel visual system"), l("Thương hiệu cần làm mới nhận diện mà không đánh mất tài sản hiện có", "Brands refreshing identity without losing existing equity"), l("Đội marketing cần bộ tài nguyên dễ mở rộng và sử dụng", "Marketing teams needing scalable, usable asset systems")],
    problems: [l("Thiết kế đẹp nhưng không truyền tải được ý tưởng chiến lược", "Beautiful design that fails to carry the strategy"), l("Ấn phẩm thiếu nhất quán khi mở rộng sang nhiều kích thước và nền tảng", "Assets lose consistency across formats and platforms"), l("Mỗi chiến dịch phải làm lại từ đầu vì thiếu hệ thống", "Every campaign restarts from zero without a system")],
    method: [{ title: l("Chốt ý tưởng trung tâm", "Define the central idea"), description: l("Tìm một ý niệm đủ rõ để dẫn dắt câu chữ, hình ảnh, chuyển động và trải nghiệm.", "Find one clear idea that can guide copy, visuals, motion and experience.") }, { title: l("Xây ngôn ngữ hình ảnh", "Build the visual language"), description: l("Thiết lập màu sắc, typography, bố cục, hình ảnh và nguyên tắc chuyển động.", "Establish color, typography, layout, imagery and motion principles.") }, { title: l("Đóng gói để vận hành", "Package for operation"), description: l("Tạo template, guideline và thư viện giúp đội ngũ triển khai nhanh mà vẫn đúng thương hiệu.", "Create templates, guidelines and libraries for fast, on-brand execution.") }],
    promise: l("Sáng tạo không dừng ở một key visual đẹp; nó cần trở thành hệ thống đủ linh hoạt để sống trên mọi điểm chạm.", "Creative should not stop at one beautiful key visual; it should become a flexible system that lives across every touchpoint."),
  },
  "performance-marketing": {
    fitFor: [l("Doanh nghiệp cần kết nối chi tiêu media với kết quả kinh doanh", "Businesses linking media spend to commercial outcomes"), l("Chiến dịch có dữ liệu nhưng chưa biến thành quyết định tối ưu", "Campaigns with data but no optimization decisions"), l("Sản phẩm cần kiểm thử thông điệp và creative có hệ thống", "Products needing systematic message and creative testing")],
    problems: [l("Tối ưu từng nền tảng nhưng thiếu cái nhìn toàn phễu", "Platform-level optimization without a full-funnel view"), l("Creative fatigue làm chi phí tăng nhưng phát hiện quá muộn", "Creative fatigue detected too late"), l("Báo cáo nhiều chỉ số nhưng khó biết hành động tiếp theo", "Reports show metrics but not the next action")],
    method: [{ title: l("Thiết kế đo lường", "Design measurement"), description: l("Thống nhất mục tiêu, sự kiện chuyển đổi, nguồn dữ liệu và nguyên tắc đọc hiệu quả.", "Align goals, conversion events, data sources and performance rules.") }, { title: l("Xây ma trận thử nghiệm", "Build the test matrix"), description: l("Kiểm thử có chủ đích giữa audience, offer, message, format và landing experience.", "Run intentional tests across audience, offer, message, format and landing experience.") }, { title: l("Ra quyết định theo nhịp", "Decide on cadence"), description: l("Duy trì chu kỳ quan sát, kết luận, phân bổ lại ngân sách và tạo creative mới.", "Maintain a cadence of observation, learning, reallocation and creative renewal.") }],
    promise: l("ANBU không chỉ mua media; chúng tôi xây vòng lặp học hỏi để mỗi đợt ngân sách tạo ra thêm hiểu biết cho đợt tiếp theo.", "ANBU does more than buy media; we build a learning loop so every budget cycle improves the next."),
  },
  "seo-content": {
    fitFor: [l("Thương hiệu muốn xây nhu cầu dài hạn thay vì chỉ phụ thuộc quảng cáo", "Brands building durable demand beyond paid media"), l("Website có nội dung nhưng chưa bao phủ hành trình tìm kiếm", "Sites with content but weak search-journey coverage"), l("Đội ngũ cần một hệ thống biên tập có ưu tiên rõ ràng", "Teams needing a prioritized editorial system")],
    problems: [l("Viết nhiều nhưng các bài cạnh tranh lẫn nhau", "Publishing more while pages compete with each other"), l("Traffic tăng nhưng không dẫn đến hành động kinh doanh", "Traffic grows without business action"), l("SEO kỹ thuật và nội dung vận hành tách rời", "Technical SEO and content operate separately")],
    method: [{ title: l("Vẽ bản đồ nhu cầu", "Map demand"), description: l("Nhóm truy vấn theo vấn đề, ý định và giai đoạn ra quyết định của khách hàng.", "Group queries by problem, intent and decision stage.") }, { title: l("Xây cụm chủ đề", "Build topic clusters"), description: l("Thiết kế trang trụ cột, bài hỗ trợ và liên kết nội bộ để tạo chiều sâu chuyên môn.", "Design pillars, supporting pages and internal links that build authority.") }, { title: l("Đo chất lượng tăng trưởng", "Measure quality growth"), description: l("Theo dõi hiển thị, tương tác, chuyển đổi và đóng góp của nội dung theo thời gian.", "Track visibility, engagement, conversion and content contribution over time.") }],
    promise: l("Mục tiêu không phải có thêm thật nhiều bài viết, mà là xây một tài sản nội dung giúp khách hàng tìm thấy, hiểu và tin thương hiệu.", "The goal is not simply more articles, but a content asset that helps customers find, understand and trust the brand."),
  },
  "web-development": {
    fitFor: [l("Thương hiệu cần website kể câu chuyện rõ và tạo lead", "Brands needing a site that tells the story and generates leads"), l("Landing page chiến dịch cần ra nhanh, đo được và dễ tối ưu", "Campaign landing pages that must launch fast and optimize easily"), l("Website hiện tại chậm, khó quản trị hoặc thiếu nền tảng SEO", "Sites that are slow, hard to manage or weak in SEO foundations")],
    problems: [l("Giao diện đẹp nhưng người dùng không biết nên làm gì tiếp", "A beautiful interface with no clear next action"), l("Nội dung, thiết kế và kỹ thuật được làm bởi ba nhóm rời rạc", "Content, design and engineering work in silos"), l("Sau bàn giao, đội nội bộ khó cập nhật", "Internal teams struggle to update after handoff")],
    method: [{ title: l("Thiết kế hành trình", "Design the journey"), description: l("Sắp xếp thông tin theo câu hỏi của người dùng và mục tiêu chuyển đổi.", "Structure information around user questions and conversion goals.") }, { title: l("Xây hệ thống giao diện", "Build the interface system"), description: l("Tạo component nhất quán, responsive và dễ mở rộng thay vì thiết kế từng trang rời.", "Create consistent, responsive components rather than isolated pages.") }, { title: l("Tối ưu & bàn giao", "Optimize and hand over"), description: l("Kiểm tra tốc độ, accessibility, SEO, analytics và hướng dẫn vận hành nội dung.", "Validate speed, accessibility, SEO and analytics, then train the content team.") }],
    promise: l("Website phải vừa là trải nghiệm thương hiệu, vừa là công cụ kinh doanh mà đội ngũ có thể tiếp tục vận hành sau khi bàn giao.", "A website should be both a brand experience and a business tool the team can operate after handoff."),
  },
  "social-media": {
    fitFor: [l("Thương hiệu cần xây kênh social từ đầu", "Brands building social channels from scratch"), l("Kênh đang đăng đều nhưng thiếu bản sắc và tương tác thật", "Channels posting regularly but lacking identity and real engagement"), l("Game/app cần vận hành cộng đồng trước, trong và sau ra mắt", "Games or apps operating communities before, during and after launch")],
    problems: [l("Nội dung chạy theo lịch nhưng không có vai trò chiến lược", "Content follows a calendar without a strategic role"), l("Mỗi bài một phong cách khiến thương hiệu khó được nhận ra", "Inconsistent posts weaken recognition"), l("Community management chỉ dừng ở trả lời bình luận", "Community management stops at replying to comments")],
    method: [{ title: l("Xác định vai trò kênh", "Define channel roles"), description: l("Làm rõ mỗi nền tảng phục vụ nhận biết, giáo dục, tương tác hay chuyển đổi.", "Clarify whether each platform drives awareness, education, engagement or conversion.") }, { title: l("Xây content engine", "Build the content engine"), description: l("Thiết kế trụ cột, series, format và nhịp xuất bản có thể duy trì lâu dài.", "Design pillars, series, formats and a sustainable publishing cadence.") }, { title: l("Nuôi cộng đồng", "Grow the community"), description: l("Quan sát tín hiệu, phản hồi có cá tính và biến câu hỏi của người dùng thành chất liệu nội dung.", "Read signals, respond with personality and turn audience questions into content.") }],
    promise: l("Một kênh social tốt không chỉ đầy bài đăng; nó tạo được nhịp điệu, tính cách và lý do để cộng đồng quay lại.", "A strong social channel is more than a feed, it has rhythm, personality and a reason for the community to return."),
  },
};
